version: 0.2

phases:
  install:
    commands:
      - echo Installing NGINX
      - sudo apt update
      - sudo apt install -y nginx
  build:
    commands:
      - echo Build started on $(date)
      - mkdir build
      - npm install
      - npm run build
      - mkdir -p var/www/html
      - cp -r build/* var/www/html
      - echo $(ls)
  post_build:
    commands:
      - echo Configuring NGINX
#      - aws s3 sync build/ s3://nginx-react-demo-app-artifacts/Nginx-React-Demo-App/build
artifacts:
  files:
    - "**/*"
