version: 0.2

phases:
  install:
    commands:
#      - echo Installing NGINX
      - sudo apt update
      - npm install
  build:
    commands:
      - echo Build started on $(date)
      - npm run build
#      - mkdir -p var/www/html
#      - cp -r build var/www/html
#      - echo $(ls)
  post_build:
    commands:
      - echo $CODEBUILD_SRC_DIR
      - echo $CODEBUILD_BUILD_ID
      - echo $CODEBUILD_LOG_PATH
      - echo $CODEBUILD_PUBLIC_BUILD_URL
#      - echo Configuring NGINX
artifacts:
  files:
    - "**/*"
